firefly-iii/data-importer

app/Services/CSV/Converter/BankDebitCredit.php

The Banking App Baniking4 offers a CSV export in the Subsemply format.
`DBIT` is the indicator for debits
@JC5

Add DBIT as debit indicator

---

app/Services/Shared/Configuration/Configuration.php

Fixes issue [#5402](https://github.com/firefly-iii/firefly-iii/issues/5402)
- Fixes setting the import date range (the date_not_after was wrongly using the date_not_before variable)
@JC5

Fix setting import date range

---

resources/views/import/004-configure/index.twig

- Update the PHP docs link to the page which explains the date format string
@JC5

Change PHP docs link

---

.env.example

Trying to make the FIDI conf file more helpful.
@JC5

Small fixes and improvements to the FIDI conf file

---

.env.example

Fix spelling (signed)

---

app/Services/CSV/Converter/Description.php
app/Services/CSV/Converter/Iban.php
app/Services/CSV/Converter/TagsComma.php
app/Services/CSV/Converter/TagsSpace.php
app/Services/Nordigen/Model/Balance.php
app/Services/Nordigen/Model/Transaction.php

Trim values for easier mapping.

---

app/Http/Controllers/Import/ConfigurationController.php
app/Http/Middleware/IsReadyForStep.php
app/Services/Nordigen/TokenManager.php
app/Services/Session/Constants.php
app/Services/Shared/Model/ImportServiceAccount.php
app/Support/Internal/CollectsAccounts.php
app/Support/Internal/MergesAccountLists.php
resources/views/import/004-configure/index.twig
resources/views/import/004-configure/partials/account-row.twig
resources/views/import/004-configure/partials/account-title-generic.twig
resources/views/import/004-configure/partials/account-title-nordigen.twig
resources/views/import/004-configure/partials/ff3-account-generic.twig
resources/views/import/004-configure/partials/ff3-account-spectre.twig

Unify Nordigen and Spectre views, better matching on account numbers.

---

app/Http/Controllers/Import/ConfigurationController.php
app/Services/Session/Constants.php
app/Services/Shared/Model/ImportServiceAccount.php
app/Support/Internal/CollectsAccounts.php
app/Support/Internal/MergesAccountLists.php
composer.lock

Clean up code, fix packages

---

app/Services/Nordigen/Request/Request.php

Fix https://github.com/firefly-iii/firefly-iii/issues/6909

---

app/Http/Controllers/Import/ConfigurationController.php

Fix missing column types.

---

app/Console/Kernel.php

Add warning for bad config variables.

---

app/Mail/ImportReportMail.php

Switch to vanity URL if present.

---

.github/workflows/cleanup.yml

Update prune workflow.

---

app/Console/HaveAccess.php

Fix allowlist variable name

---

app/Services/Shared/Import/Routine/ApiSubmitter.php

Improve logging a little bit.

---

.github/workflows/qodana.yml
config/importer.php
qodana.yaml

Add support for Qodana

---

.ci/php-cs-fixer/composer.json
.ci/php-cs-fixer/composer.lock
app/Services/CSV/Conversion/Task/Accounts.php
changelog.md
config/importer.php

chore: update meta data for new release.

---

app/Services/CSV/Conversion/Task/Accounts.php

Attempt to fix https://github.com/firefly-iii/firefly-iii/issues/7214

Attempt at #7214

---

app/Console/HaveAccess.php

Also do partial matching on paths.

---

app/Console/HaveAccess.php
changelog.md
config/importer.php

chore: Update meta files for v1.2.1

---

app/Mail/ImportReportMail.php
resources/views/emails/import/report.blade.php

Fix https://github.com/firefly-iii/firefly-iii/issues/7225

---

.ci/php-cs-fixer/composer.lock
changelog.md
config/importer.php

Meta data for new release.

---

app/Handlers/Events/ImportedTransactionsEventHandler.php

Fixes issue https://github.com/firefly-iii/firefly-iii/issues/7264 (if relevant)
-
-
-
@JC5

Fix issue https://github.com/firefly-iii/firefly-iii/issues/7264

---

config/mail.php

Fixes issue [#5996](https://github.com/firefly-iii/firefly-iii/issues/5996)
- brings firefly-iii fix to data-importer
@JC5

fix: disable verification check for unencrypted smtp

---

composer.lock

fix: repair the composer.lock file.

---

.github/support.md
changelog.md
readme.md
resources/views/errors/exception.twig
resources/views/import/002-authenticate/index.twig
resources/views/import/003-upload/index.twig
resources/views/import/004-configure/index.twig
resources/views/import/005-roles/index-csv.twig
resources/views/import/009-selection/index.twig
resources/views/import/011-connection/index.twig
resources/views/layout/default.twig
resources/views/token/index.twig

fix: documentation links

---

resources/views/import/003-upload/index.twig

limit uploads to supported file types, client side
should probably filter in upload routine as well.
@JC5

basic client side file extension filter for upload file

---

app/Http/Controllers/Import/UploadController.php

Seems like everyone is tripping over "r"-s lol
@JC5

fix mocking typo

---

.env.example

moved variable to top of file near other URL variables
gave example

Update .env.example, ASSET_URL moved, example given

---

app/Services/CSV/Converter/BankDebitCredit.php

This PR fixes issue:
Added support for the credit/debit format used by Banco Bolivariano (Ecuador)
-
-
-
@JC5

Added support for generic-debit-credit in Banco Bolivariano's format
